### ISSUE TITLE
FedProx can not support CosineAnnealingLR in pytorch runtime

### ISSUE THREAD

**Issue by ChengMingZhang-ZTE** [neursafe/federated-learning#29]
[2022-06-15 01:46:59,919] linux_executor.py[line:66] ERROR: Traceback (most recent call last):
  File "train.py", line 112, in <module>
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=200)
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py", line 504, in __init__
    super(CosineAnnealingLR, self).__init__(optimizer, last_epoch, verbose)
  File "/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py", line 37, in __init__
    group.setdefault('initial_lr', group['lr'])
KeyError: 'lr'

**Comment by ChengMingZhang-ZTE** [comment]
#60 fix this issue
