### ISSUE TITLE
kubernetes部署task-manager时报错

### ISSUE THREAD

**Issue by zhaohainan666** [neursafe/federated-learning#37]
/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
[2022-06-20 09:21:05,014] postgre.py[line:87] ERROR: PostgreSQL create failed, error code: None, error info: fe_sendauth: no password supplied
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/libs/db/postgre/postgre.py", line 82, in connect
    connect_timeout=CONNECTION_TIMEOUT)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/libs/db/postgre/postgre.py", line 82, in connect
    connect_timeout=CONNECTION_TIMEOUT)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/client/app.py", line 105, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/client/app.py", line 100, in main
    client = Client(config_dic)
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/client/client.py", line 122, in __init__
    self.__task_manager = TaskManager(config)
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/client/task_manager.py", line 44, in __init__
    self.__resource_manager = ResourceManager()
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/resource_manager/rm.py", line 54, in __init__
    pass_word=const.DB_PASSWORD).\
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/libs/db/db_factory.py", line 40, in create_db
    return PostgreSQL(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/libs/db/postgre/postgre.py", line 136, in __init__
    self.__client.connect()
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/libs/db/postgre/postgre.py", line 88, in connect
    raise errors.DataBaseError(err_msg)
neursafe_fl.python.libs.db.errors.DataBaseError: PostgreSQL create failed, error code: None, error info: fe_sendauth: no password supplied

有两个错误：

1. 用户端没有说要部署pg，但是代码里确有pg
2. setup.json里没有关于pg的任何配置的说明，只根据你们提供的required 参与，根本无法部署

**Comment by ChengMingZhang-ZTE** [comment]
#55 optimize cluster deploy, user only need to configure an unified config file, we provide a script to generate all delpoyment files. Please refer to https://github.com/neursafe/federated-learning/blob/main/docs/cluster_deploy_zh.md
