### ISSUE TITLE
安装nsfl-ctl时报错

### ISSUE THREAD

**Issue by zhaohainan666** [neursafe/federated-learning#43]
Build proto successfully.
INFO: Repository rules_python instantiated at:
  /root/zhn/federate/federated-learning-main/WORKSPACE:2:15: in <toplevel>
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/cb5c4cd825dbca79ce4440ddff3ab78c/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_python':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/cb5c4cd825dbca79ce4440ddff3ab78c/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
		update = _clone_or_update(ctx)
	File "/root/.cache/bazel/_bazel_root/cb5c4cd825dbca79ce4440ddff3ab78c/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
		git_ = git_repo(ctx, directory)
	File "/root/.cache/bazel/_bazel_root/cb5c4cd825dbca79ce4440ddff3ab78c/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/root/.cache/bazel/_bazel_root/cb5c4cd825dbca79ce4440ddff3ab78c/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
		init(ctx, git_repo)
	File "/root/.cache/bazel/_bazel_root/cb5c4cd825dbca79ce4440ddff3ab78c/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
		_error(ctx.name, cl, st.stderr)
	File "/root/.cache/bazel/_bazel_root/cb5c4cd825dbca79ce4440ddff3ab78c/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init /root/.cache/bazel/_bazel_root/cb5c4cd825dbca79ce4440ddff3ab78c/external/rules_python' while working with @rules_python:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
ERROR: no such package '@rules_python//python': error running 'git init /root/.cache/bazel/_bazel_root/cb5c4cd825dbca79ce4440ddff3ab78c/external/rules_python' while working with @rules_python:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
INFO: Elapsed time: 0.159s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

需要手动安装git

**Comment by ChengMingZhang-ZTE** [comment]
Before installation, you should git clone the code, so you should already installed git in your environment
