### ISSUE TITLE
Resource config 'gpu' cause running execption

### ISSUE THREAD

**Issue by kewenwang-ai** [neursafe/federated-learning#58]
When add the resource field in the job config. the task manager will start pod failed.

1073741824(0.195). (byte)
[2022-07-06 02:04:25,913] validation.py[line:180] ERROR: Cpu, gpu, memory all are 0, no resource request.
[2022-07-06 02:04:25,913] client.py[line:52] ERROR: Cpu, gpu, memory all are 0, no resource request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/client/client.py", line 43, in Train
    stream, validate_func=validate_task_info)
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/trans/grpc_call.py", line 141, in unpackage_stream
    validate_func(config)
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/client/validation.py", line 104, in validate_task_info
    __validate_resource(request.spec.resource)
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/client/validation.py", line 142, in __validate_resource
    raise_exception("Cpu, gpu, memory all are 0, no resource request.")
  File "/usr/local/lib/python3.7/site-packages/neursafe_fl/python/client/validation.py", line 181, in raise_exception
    raise ParameterError(err_msg)
neursafe_fl.python.client.validation.ParameterError: Cpu, gpu, memory all are 0, no resource request.

**Comment by kewenwang-ai** [comment]
The reason for this error is because the validation code:
neursafe_fl/python/client/validation.py   FUNCTION :  __validate_resource
judge error
